SELECT MEMBER_NO , MEMBER_ID , MEMBER_NAME , GENDER ,
 TO_CHAR(ENROLL_DATE, 'YYYY"년" MM"월" DD"일" HH24:MI:SS') ENROLL_DATE 
FROM TB_MEMBER TM 
WHERE MEMBER_ID = ?
AND MEMBER_PW = ?;

-- 회원 목록 조회
SELECT MEMBER_NO ,MEMBER_ID ,MEMBER_PW , MEMBER_NAME ,
DECODE(GENDER, 'M', '남성', 'F' , '여성') AS GENDER,
 TO_CHAR(ENROLL_DATE, 'YYYY"년" MM"월" DD"일" HH24:MI:SS') ENROLL_DATE 
FROM  TB_MEMBER TM 
ORDER BY MEMBER_NO DESC ;


INSERT INTO TB_MEMBER TM 
VALUES(SEQ_MEMBER_NO.NEXTVAL ,? ,? ,? ,? ,DEFAULT)









