-- 시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE; -- 회원번호
CREATE SEQUENCE SEQ_BOARD_NO NOCACHE;	-- 게시글번호
CREATE SEQUENCE SEQ_COMMENT_NO NOCACHE; -- 댓글번호


INSERT INTO MEMBER
VALUES(SEQ_MEMBER_NO.NEXTVAL,
  'mem01@google.com', 
  '123123',
  '1번회원',
  '01012341234',
  '서울시 중구',
 DEFAULT, DEFAULT);
 
SELECT * FROM "MEMBER" m ;
ROLLBACK;
-- 이메일, 비밀번호가 일치하는 회원의
-- 닉네임, 전화번호, 주소 수정
UPDATE MEMBER
SET MEMBER_NICKNAME = '변경된 닉네임',
MEMBER_TEL = '01011112222',
MEMBER_ADDRESS = '경기도 수원시'
WHERE MEMBER_EMAIL = 'mem01@google.com'
AND MEMBER_PW  = '123123'
;


DELETE FROM MEMBER 
WHERE MEMBER_EMAIL = '이메일'
AND MEMBER_PW = '비밀번호';



UPDATE MEMBER
SET MEMBER_PW = '변경할비밀번호'
WHERE MEMBER_EMAIL = '이메일'
AND MEMBER_PW = '비밀번호';

SELECT * FROM MEMBER;






SELECT MEMBER_NO ,MEMBER_NICKNAME ,MEMBER_TEL ,MEMBER_ADDRESS ,
	TO_CHAR(ENROLL_DATE, 'YYYY"년" MM"월" DD"일" HH24:MI:SS' ) ENROLL_DATE
FROM MEMBER 
WHERE MEMBER_EMAIL = ''
AND MEMBER_PW = ''
AND MEMBER_DEL_FL = 'N'
;

SELECT * FROM MEMBER
ORDER BY MEMBER_NO DESC;
;

UPDATE MEMBER SET 
MEMBER_NICKNAME = '별명',
MEMBER_TEL = '01022223333'
WHERE MEMBER_NO = 5;


SELECT * FROM BOARD B ;
INSERT INTO BOARD VALUES (SEQ_BOARD_NO.NEXTVAL, 
'제목1',
'내용1',
DEFAULT,
DEFAULT,
DEFAULT,
3);

UPDATE MEMBER SET MEMBER_DEL_FL = 'N';

SELECT BOARD_NO, BOARD_TITLE, 
	TO_CHAR(B_CREATE_DATE, 'YYYY-MM-DD HH24:MI:SS') B_CREATE_DATE,
	READ_COUNT, MEMBER_NO, MEMBER_NICKNAME 
FROM BOARD 
JOIN MEMBER USING(MEMBER_NO)
WHERE BOARD_DEL_FL = 'N'
ORDER BY BOARD_NO DESC;